#!/bin/sh
if [ -n "$1" ]; then
    setxkbmap $1
else
    layout=$(setxkbmap -query | awk 'END{print $2}')
    case $layout in
        dk)
                setxkbmap us
            ;;
        us)
                setxkbmap dk
            ;;
	*)
	        setxkbmap us
	    ;;
    esac
fi
